//! all-slain locations_respawn.py (MIT); license retained beside this file
pub const LOCATIONS: &[(&str, &str)] = &[
    ("Pyro1", "Pyro I"),
    (
        "Pyro1_ASD_Monorail_Compound_1A",
        "Lazarus Transport Hub Phoenix-I",
    ),
    (
        "Pyro1_ASD_Monorail_Compound_1B",
        "Lazarus Transport Hub Phoenix-II",
    ),
    (
        "Pyro1_ASD_Monorail_Compound_1C",
        "Lazarus Transport Hub Phoenix-III",
    ),
    (
        "Pyro1_ASD_Monorail_Compound_2A",
        "Lazarus Transport Hub Tithonus-I",
    ),
    (
        "Pyro1_ASD_Monorail_Compound_2B",
        "Lazarus Transport Hub Tithonus-II",
    ),
    (
        "Pyro1_ASD_Monorail_Compound_2C",
        "Lazarus Transport Hub Tithonus-III",
    ),
    (
        "Pyro1_ASD_Research_Facility_1A",
        "Lazarus Complex Phoenix-I",
    ),
    (
        "Pyro1_ASD_Research_Facility_1B",
        "Lazarus Complex Phoenix-II",
    ),
    (
        "Pyro1_ASD_Research_Facility_1C",
        "Lazarus Complex Phoenix-III",
    ),
    (
        "Pyro1_ASD_Research_Facility_2A",
        "Lazarus Complex Tithonus-I",
    ),
    (
        "Pyro1_ASD_Research_Facility_2B",
        "Lazarus Complex Tithonus-II",
    ),
    (
        "Pyro1_ASD_Research_Facility_2C",
        "Lazarus Complex Tithonus-III",
    ),
    ("Pyro1_L1", "PYR1 L1"),
    ("Pyro1_L1_01", "PYR1 L1-A"),
    ("Pyro1_L1_02", "PYR1 L1-B"),
    ("Pyro1_L1_03", "PYR1 L1-C"),
    ("Pyro1_L1_04", "PYR1 L1-D"),
    ("Pyro1_L2", "PYR1 L2"),
    ("Pyro1_L2_01", "PYR1 L2-A"),
    ("Pyro1_L2_02", "PYR1 L2-B"),
    ("Pyro1_L2_03", "PYR1 L2-C"),
    ("Pyro1_L2_04", "PYR1 L2-D"),
    ("Pyro1_L3", "PYR1 L3"),
    ("Pyro1_L3_01", "PYR1 L3-A"),
    ("Pyro1_L3_02", "PYR1 L3-B"),
    ("Pyro1_L3_03", "PYR1 L3-C"),
    ("Pyro1_L3_04", "PYR1 L3-D"),
    ("Pyro1_L4", "PYR1 L4"),
    ("Pyro1_L4_01", "PYR1 L4-A"),
    ("Pyro1_L4_02", "PYR1 L4-B"),
    ("Pyro1_L4_03", "PYR1 L4-C"),
    ("Pyro1_L4_04", "PYR1 L4-D"),
    ("Pyro1_L5", "PYR1 L5"),
    ("Pyro1_L5_01", "PYR1 L5-A"),
    ("Pyro1_L5_02", "PYR1 L5-B"),
    ("Pyro1_L5_03", "PYR1 L5-C"),
    ("Pyro1_L5_04", "PYR1 L5-D"),
    ("Pyro1_Outpost_col_m_drlct_occ_002", "Derelict Outpost"),
    ("Pyro1_Outpost_col_m_scrp_otlw_001", "Rustville"),
    ("Pyro1_Outpost_col_s_drlct_occ_003", "Derelict Outpost"),
    ("Pyro1_Outpost_col_s_mng_indy_001", "Stag's Rut"),
    ("Pyro1_Outpost_col_xs_dpt_otlw_001", "Gray Gardens Depot"),
    ("Pyro2", "Monox"),
    ("Pyro2_L1", "PYR2 L1"),
    ("Pyro2_L1_01", "PYR2 L1-A"),
    ("Pyro2_L1_02", "PYR2 L1-B"),
    ("Pyro2_L1_03", "PYR2 L1-C"),
    ("Pyro2_L1_04", "PYR2 L1-D"),
    ("Pyro2_L2", "PYR2 L2"),
    ("Pyro2_L2_01", "PYR2 L2-A"),
    ("Pyro2_L2_02", "PYR2 L2-B"),
    ("Pyro2_L2_03", "PYR2 L2-C"),
    ("Pyro2_L2_04", "PYR2 L2-D"),
    ("Pyro2_L3", "PYR2 L3"),
    ("Pyro2_L3_01", "PYR2 L3-A"),
    ("Pyro2_L3_02", "PYR2 L3-B"),
    ("Pyro2_L3_03", "PYR2 L3-C"),
    ("Pyro2_L3_04", "PYR2 L3-D"),
    ("Pyro2_L4", "PYR2 L4"),
    ("Pyro2_L4_01", "PYR2 L4-A"),
    ("Pyro2_L4_02", "PYR2 L4-B"),
    ("Pyro2_L4_03", "PYR2 L4-C"),
    ("Pyro2_L4_04", "PYR2 L4-D"),
    ("Pyro2_L5", "PYR2 L5"),
    ("Pyro2_L5_01", "PYR2 L5-A"),
    ("Pyro2_L5_02", "PYR2 L5-B"),
    ("Pyro2_L5_03", "PYR2 L5-C"),
    ("Pyro2_L5_04", "PYR2 L5-D"),
    (
        "Pyro2_MiningCompound_drlct_001_a",
        "Vasko Mining Compound-A",
    ),
    (
        "Pyro2_MiningCompound_drlct_001_b",
        "Vasko Mining Compound-B",
    ),
    (
        "Pyro2_MiningCompound_drlct_001_c",
        "Vasko Mining Compound-C",
    ),
    (
        "Pyro2_MiningCompound_drlct_001_d",
        "Vasko Mining Compound-D",
    ),
    (
        "Pyro2_MiningCompound_drlct_002_a",
        "Fillmore Mining Compound-A",
    ),
    (
        "Pyro2_MiningCompound_drlct_002_b",
        "Fillmore Mining Compound-B",
    ),
    (
        "Pyro2_MiningCompound_drlct_002_c",
        "Fillmore Mining Compound-C",
    ),
    (
        "Pyro2_MiningCompound_drlct_002_d",
        "Fillmore Mining Compound-D",
    ),
    (
        "Pyro2_Outpost_col_m_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_m_drlct_otpst_occ_002",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_m_drlct_otpst_occ_003",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_m_drlct_otpst_occ_004",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_m_drlct_otpst_occ_005",
        "Derelict Outpost",
    ),
    ("Pyro2_Outpost_col_m_mng_otlw_002", "Last Ditch"),
    ("Pyro2_Outpost_col_m_scrp_indy_001", "Sunset Mesa"),
    ("Pyro2_Outpost_col_m_trdp_indy_001", "Jackson's Swap"),
    (
        "Pyro2_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_s_drlct_otpst_occ_002",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_s_drlct_otpst_occ_003",
        "Derelict Outpost",
    ),
    (
        "Pyro2_Outpost_col_s_drlct_otpst_unoc_001",
        "Derelict Outpost",
    ),
    ("Pyro2_Outpost_col_s_mng_indy_001", "Yang's Place"),
    ("Pyro2_Outpost_col_s_mng_otlw_001", "Ostler's Claim"),
    ("Pyro2_Outpost_col_s_trdpst_otlw_001", "Arid Reach"),
    ("Pyro2_Outpost_col_xs_dpt_otlw_001", "Slowburn Depot"),
    ("Pyro2_Racetrack_FoolsRun", "Fool's Run"),
    ("Pyro3", "Bloom"),
    ("Pyro3_L1", "PYR3 L1"),
    ("Pyro3_L1_01", "PYR3 L1-A"),
    ("Pyro3_L1_02", "PYR3 L1-B"),
    ("Pyro3_L1_03", "PYR3 L1-C"),
    ("Pyro3_L1_04", "PYR3 L1-D"),
    ("Pyro3_L2", "PYR3 L2"),
    ("Pyro3_L2_01", "PYR3 L2-A"),
    ("Pyro3_L2_02", "PYR3 L2-B"),
    ("Pyro3_L2_03", "PYR3 L2-C"),
    ("Pyro3_L2_04", "PYR3 L2-D"),
    ("Pyro3_L3", "PYR3 L3"),
    ("Pyro3_L3_01", "PYR3 L3-A"),
    ("Pyro3_L3_02", "PYR3 L3-B"),
    ("Pyro3_L3_03", "PYR3 L3-C"),
    ("Pyro3_L3_04", "PYR3 L3-D"),
    ("Pyro3_L4", "PYR3 L4"),
    ("Pyro3_L4_01", "PYR3 L4-A"),
    ("Pyro3_L4_02", "PYR3 L4-B"),
    ("Pyro3_L4_03", "PYR3 L4-C"),
    ("Pyro3_L4_04", "PYR3 L4-D"),
    ("Pyro3_L5", "PYR3 L5"),
    ("Pyro3_L5_01", "PYR3 L5-A"),
    ("Pyro3_L5_02", "PYR3 L5-B"),
    ("Pyro3_L5_03", "PYR3 L5-C"),
    ("Pyro3_L5_04", "PYR3 L5-D"),
    ("Pyro3_Outpost_col_m_frm_indy_001", "Shepherd's Rest"),
    ("Pyro3_outpost_col_m_hmstd_indy_001", "Narena's Rest"),
    ("Pyro3_Outpost_col_m_hmstd_otlw_001", "Shadowfall"),
    ("Pyro3_Outpost_col_m_mng_indy_001", "Bueno Ravine"),
    ("Pyro3_Outpost_col_m_trdpst_otlw_006", "The Golden Riviera"),
    (
        "Pyro3_Outpost_col_s_drlct_optst_occ_001",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_optst_occ_002",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_optst_occ_007",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_otpst_occ_004",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_otpst_occ_007",
        "Derelict Outpost",
    ),
    (
        "Pyro3_Outpost_col_s_drlct_otpst_unoc_007",
        "Derelict Outpost",
    ),
    ("Pyro3_Outpost_col_s_frm_otlw_002", "The Yard"),
    ("Pyro3_Outpost_col_s_mng_otlw_001", "Carver's Ridge"),
    ("Pyro3_Outpost_col_s_scrp_otlw_002", "Windfall"),
    ("Pyro3_Outpost_col_s_trdpst_indy_002", "Frigid Knot"),
    ("Pyro3_Outpost_col_xs_dpt_otlw_001", "Prospect Depot"),
    ("Pyro4", "Pyro IV"),
    ("Pyro4_ASD_Data_Facility_1", "Farro Data Center I"),
    ("Pyro4_ASD_Data_Facility_10", "Farro Data Center X"),
    ("Pyro4_ASD_Data_Facility_2", "Farro Data Center II"),
    ("Pyro4_ASD_Data_Facility_3", "Farro Data Center III"),
    ("Pyro4_ASD_Data_Facility_4", "Farro Data Center IV"),
    ("Pyro4_ASD_Data_Facility_5", "Farro Data Center V"),
    ("Pyro4_ASD_Data_Facility_6", "Farro Data Center VI"),
    ("Pyro4_ASD_Data_Facility_7", "Farro Data Center VII"),
    ("Pyro4_ASD_Data_Facility_8", "Farro Data Center VIII"),
    ("Pyro4_ASD_Data_Facility_9", "Farro Data Center IX"),
    (
        "Pyro4_Outpost_col_m_drlct_otpst_occ_002",
        "Derelict Outpost",
    ),
    ("Pyro4_Outpost_col_m_scrp_indy_001", "Chawla's Beach"),
    ("Pyro4_Outpost_col_m_trdpst_indy_001", "Sacren's Plot"),
    ("Pyro4_Outpost_col_m_trdpst_otlw_001", "Fallow Field"),
    (
        "Pyro4_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro4_Outpost_col_s_trdpst_otlw_001", "Goner's Deal"),
    ("Pyro4_Outpost_col_xs_dpt_otlw_001", "Dinger's Depot"),
    ("Pyro5", "Pyro V"),
    ("Pyro5_L1", "PYR5 L1"),
    ("Pyro5_L1_01", "PYR5 L1-A"),
    ("Pyro5_L1_02", "PYR5 L1-B"),
    ("Pyro5_L1_03", "PYR5 L1-C"),
    ("Pyro5_L1_04", "PYR5 L1-D"),
    ("Pyro5_L2", "PYR5 L2"),
    ("Pyro5_L2_01", "PYR5 L2-A"),
    ("Pyro5_L2_02", "PYR5 L2-B"),
    ("Pyro5_L2_03", "PYR5 L2-C"),
    ("Pyro5_L2_04", "PYR5 L2-D"),
    ("Pyro5_L3", "PYR5 L3"),
    ("Pyro5_L3_01", "PYR5 L3-A"),
    ("Pyro5_L3_02", "PYR5 L3-B"),
    ("Pyro5_L3_03", "PYR5 L3-C"),
    ("Pyro5_L3_04", "PYR5 L3-D"),
    ("Pyro5_L4", "PYR5 L4"),
    ("Pyro5_L4_01", "PYR5 L4-A"),
    ("Pyro5_L4_02", "PYR5 L4-B"),
    ("Pyro5_L4_03", "PYR5 L4-C"),
    ("Pyro5_L4_04", "PYR5 L4-D"),
    ("Pyro5_L5", "PYR5 L5"),
    ("Pyro5_L5_01", "PYR5 L5-A"),
    ("Pyro5_L5_02", "PYR5 L5-B"),
    ("Pyro5_L5_03", "PYR5 L5-C"),
    ("Pyro5_L5_04", "PYR5 L5-D"),
    ("Pyro5a_Ignis", "Ignis"),
    ("Pyro5a_OLP_001", "Lamina OLP"),
    (
        "Pyro5a_Outpost_col_m_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro5a_Outpost_col_m_trdpst_otlw_001", "Ashland"),
    ("Pyro5a_Outpost_col_s_trdpst_indy_001", "Kabir's Post"),
    (
        "Pyro5b_Outpost_col_m_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro5b_Outpost_col_m_scrp_otlw_001", "Seer's Canyon"),
    ("Pyro5b_Vatra", "Vatra"),
    ("Pyro5c_Adir", "Adir"),
    ("Pyro5c_Outpost_col_m_hmstd_indy_001", "Prophet's Peak"),
    (
        "Pyro5c_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro5d_Fairo", "Fairo"),
    (
        "Pyro5d_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro5d_Outpost_col_xs_dpt_otlw_001", "Feo Canyon Depot"),
    ("Pyro5e_Fuego", "Fuego"),
    (
        "Pyro5e_MiningCompound_drlct_001_a",
        "Redfield Mining Compound-A",
    ),
    (
        "Pyro5e_MiningCompound_drlct_001_b",
        "Redfield Mining Compound-B",
    ),
    (
        "Pyro5e_MiningCompound_drlct_001_c",
        "Redfield Mining Compound-C",
    ),
    (
        "Pyro5e_MiningCompound_drlct_001_d",
        "Redfield Mining Compound-D",
    ),
    (
        "Pyro5e_MiningCompound_drlct_002_a",
        "Dezaki Mining Compound-A",
    ),
    (
        "Pyro5e_MiningCompound_drlct_002_b",
        "Dezaki Mining Compound-B",
    ),
    (
        "Pyro5e_MiningCompound_drlct_002_c",
        "Dezaki Mining Compound-C",
    ),
    (
        "Pyro5e_MiningCompound_drlct_002_d",
        "Dezaki Mining Compound-D",
    ),
    (
        "Pyro5e_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    (
        "Pyro5f_Outpost_col_s_drlct_otpst_occ_001",
        "Derelict Outpost",
    ),
    ("Pyro5f_Vuur", "Vuur"),
    ("Pyro6", "Terminus"),
    ("Pyro6_L1", "PYR6 L1"),
    ("Pyro6_L1_01", "PYR6 L1-A"),
    ("Pyro6_L1_02", "PYR6 L1-B"),
    ("Pyro6_L1_03", "PYR6 L1-C"),
    ("Pyro6_L1_04", "PYR6 L1-D"),
    ("Pyro6_L1_Clinic", "P6 L1_Clinic"),
    ("Pyro6_L1_Habs", "P6 L1_Habs"),
    ("Pyro6_L2", "PYR6 L2"),
    ("Pyro6_L2_01", "PYR6 L2-A"),
    ("Pyro6_L2_02", "PYR6 L2-B"),
    ("Pyro6_L2_03", "PYR6 L2-C"),
    ("Pyro6_L2_04", "PYR6 L2-D"),
    ("Pyro6_L3", "PYR6 L3"),
    ("Pyro6_L3_01", "PYR6 L3-A"),
    ("Pyro6_L3_02", "PYR6 L3-B"),
    ("Pyro6_L3_03", "PYR6 L3-C"),
    ("Pyro6_L3_04", "PYR6 L3-D"),
    ("Pyro6_L4", "PYR6 L4"),
    ("Pyro6_L4_01", "PYR6 L4-A"),
    ("Pyro6_L4_02", "PYR6 L4-B"),
    ("Pyro6_L4_03", "PYR6 L4-C"),
    ("Pyro6_L4_04", "PYR6 L4-D"),
    ("Pyro6_L5", "PYR6 L5"),
    ("Pyro6_L5_01", "PYR6 L5-A"),
    ("Pyro6_L5_02", "PYR6 L5-B"),
    ("Pyro6_L5_03", "PYR6 L5-C"),
    ("Pyro6_L5_04", "PYR6 L5-D"),
    (
        "Pyro6_Outpost_col_m_drlct_otpst_occ_003",
        "Derelict Outpost",
    ),
    (
        "Pyro6_Outpost_col_m_drlct_otpst_unoc_001",
        "Derelict Outpost",
    ),
    ("Pyro6_Outpost_col_m_frm_otlw_001", "Scarper's Turn"),
    ("Pyro6_Outpost_col_m_scrp_otlw_001", "Last Landings"),
    ("Pyro6_Outpost_col_m_trdpst_indy_001", "Canard View"),
    (
        "Pyro6_Outpost_col_s_drlct_otpst_occ_003",
        "Derelict Outpost",
    ),
    (
        "Pyro6_Outpost_col_s_drlct_otpst_unoc_001",
        "Derelict Outpost",
    ),
    ("Pyro6_Outpost_col_s_frm_indy_001", "Bullock's Reach"),
    ("Pyro6_Outpost_col_s_frm_otlw_001", "Kinder Plots"),
    ("Pyro6_Outpost_col_s_hmstd_otlw_001", "Stonetree"),
    ("Pyro6_Outpost_col_s_scrp_indy_001", "Supply Gap"),
    ("Pyro6_Outpost_col_s_trdpst_indy_001", "Blackrock Exchange"),
    ("Pyro6_Outpost_col_s_trdpst_otlw_001", "Rough Landing"),
    ("Pyro6_Outpost_col_xs_dpt_otlw_001", "Watcher's Depot"),
    ("Pyro_asteroidbeltA", "Akiro Cluster"),
    ("Pyro_JumpPoint_Cano", "Pyro - Cano Jump Point"),
    ("Pyro_JumpPoint_Castra", "Pyro - Castra Jump Point"),
    ("Pyro_JumpPoint_Hadrian", "Pyro - Hadrian Jump Point"),
    ("Pyro_JumpPoint_Nyx", "Pyro - Nyx Jump Point"),
    ("Pyro_JumpPoint_Oso", "Pyro - Oso Jump Point"),
    ("Pyro_JumpPoint_Stanton", "Pyro-Stanton Jump Point"),
    ("Pyro_JumpPoint_Terra", "Pyro - Terra Jump Point"),
    ("Pyro_MiningStation", "MINING STATION"),
    ("Pyro_ruinstation", "Ruin Station"),
    ("Pyro_ServiceStation", "SERVICE STATION"),
    ("Pyro_Stanton_JPStation", "Stanton Gateway"),
    ("Pyro_System", "PYRO SYSTEM"),
    ("PyroStar", "Pyro"),
    ("PyroSystem", "Pyro"),
    ("RR_ARC_L1", "ARC-L1 Wide Forest Station"),
    ("RR_ARC_L1_clinic", "ARC-L1 Wide Forest Clinic"),
    ("RR_ARC_L2", "ARC-L2 Lively Pathway Station"),
    ("RR_ARC_L2_clinic", "ARC-L2 Lively Pathway Clinic"),
    ("RR_ARC_L3", "ARC-L3 Modern Express Station"),
    ("RR_ARC_L3_clinic", "ARC-L3 Modern Express Clinic"),
    ("RR_ARC_L4", "ARC-L4 Faint Glen Station"),
    ("RR_ARC_L4_clinic", "ARC-L4 Faint Glen Clinic"),
    ("RR_ARC_L5", "ARC-L5 Yellow Core Station"),
    ("RR_ARC_L5_clinic", "ARC-L5 Yellow Core Clinic"),
    ("RR_Clinic", "Kel-To Rx Clinic"),
    ("RR_CRU_L1", "CRU-L1 Ambitious Dream Station"),
    ("RR_CRU_L1_clinic", "CRU-L1 Ambitious Dream Clinic"),
    ("RR_CRU_L4", "CRU-L4 Shallow Fields Station"),
    ("RR_CRU_L4_clinic", "CRU-L4 Shallow Fields Clinic"),
    ("RR_CRU_L5", "CRU-L5 Beautiful Glen Station"),
    ("RR_CRU_L5_clinic", "CRU-L5 Beautiful Glen Clinic"),
    ("RR_HUR_L1", "HUR-L1 Green Glade Station"),
    ("RR_HUR_L1_clinic", "HUR-L1 Green Glade Clinic"),
    ("RR_HUR_L2", "HUR-L2 Faithful Dream Station"),
    ("RR_HUR_L2_clinic", "HUR-L2 Faithful Dream Clinic"),
    ("RR_HUR_L3", "HUR-L3 Thundering Express Station"),
    ("RR_HUR_L3_clinic", "HUR-L3 Thundering Express Clinic"),
    ("RR_HUR_L4", "HUR-L4 Melodic Fields Station"),
    ("RR_HUR_L4_clinic", "HUR-L4 Melodic Fields Clinic"),
    ("RR_HUR_L5", "HUR-L5 High Course Station"),
    ("RR_HUR_L5_clinic", "HUR-L5 High Course Clinic"),
    ("RR_MIC_L1", "MIC-L1 Shallow Frontier Station"),
    ("RR_MIC_L1_clinic", "MIC-L1 Shallow Frontier Clinic"),
    ("RR_MIC_L2", "MIC-L2 Long Forest Station"),
    ("RR_MIC_L2_clinic", "MIC-L2 Long Forest Clinic"),
    ("RR_MIC_L3", "MIC-L3 Endless Odyssey Station"),
    ("RR_MIC_L3_clinic", "MIC-L3 Endless Odyssey Clinic"),
    ("RR_MIC_L4", "MIC-L4 Red Crossroads Station"),
    ("RR_MIC_L4_clinic", "MIC-L4 Red Crossroads Clinic"),
    ("RR_MIC_L5", "MIC-L5 Modern Icarus Station"),
    ("RR_MIC_L5_clinic", "MIC-L5 Modern Icarus Clinic"),
    ("RR_P1_L2", "PYAM-FARSTAT-1-2"),
    ("RR_P1_L3", "PYAM-FARSTAT-1-3"),
    ("RR_P1_L5", "PYAM-FARSTAT-1-5"),
    ("RR_P2", "PYAM-FARSTAT-2-0"),
    ("RR_P2_L3", "PYAM-FARSTAT-2-3"),
    ("RR_P2_L4", "Checkmate"),
    ("RR_P2_L4_Clinic", "Checkmate Clinic"),
    ("RR_P3", "Orbituary"),
    ("RR_P3_Clinic", "Orbituary Clinic"),
    ("RR_P3_L1", "Starlight Service Station"),
    ("RR_P3_L1_Clinic", "Starlight Clinic"),
    ("RR_P3_L3", "Patch City"),
    ("RR_P3_L3_Clinic", "Patch City Clinic"),
    ("RR_P3_L5", "PYAM-FARSTAT-3-5"),
    ("RR_P5_L1", "PYAM-FARSTAT-5-1"),
    ("RR_P5_L2", "Gaslight"),
    ("RR_P5_L2_Clinic", "Gaslight Clinic"),
    ("RR_P5_L3", "PYAM-FARSTAT-5-3"),
    ("RR_P5_L4", "Rod's Fuel 'N Supplies"),
    ("RR_P5_L4_Clinic", "Rod's Clinic"),
    ("RR_P5_L5", "Rat's Nest"),
    ("RR_P5_L5_Clinic", "Rat's Nest Clinic"),
    ("RR_P6", "Ruin Station"),
    ("RR_P6_Clinic", "Ruin Clinic"),
    ("RR_P6_L2", "PYAM-FARSTAT-6-2"),
    ("RR_P6_L3", "Endgame"),
    ("RR_P6_L3_Clinic", "Endgame Clinic"),
    ("RR_P6_L4", "Dudley & Daughters"),
    ("RR_P6_L4_Clinic", "Dudley Clinic"),
    ("RR_P6_L5", "Megumi Refueling"),
    ("RR_P6_L5_Clinic", "Megumi Clinic"),
    ("Stanton1", "Hurston"),
    ("Stanton1_Cave_Aband_01", "HDES-Calthrope (NA)"),
    ("Stanton1_CommArray_001", "Comm Array ST1-61"),
    ("Stanton1_CommArray_002", "Comm Array ST1-13"),
    ("Stanton1_CommArray_003", "Comm Array ST1-92"),
    ("Stanton1_CommArray_004", "Comm Array ST1-48"),
    ("Stanton1_CommArray_005", "Comm Array ST1-02"),
    ("Stanton1_Courier_Org", "Stanton1_Courier_Org"),
    (
        "Stanton1_CRAS_UGF_001",
        "Cry-Astro Hurston Processing Plant 19-02",
    ),
    (
        "Stanton1_CVLC_UGF_002",
        "Covalex Distribution Center S1DC06",
    ),
    (
        "Stanton1_CVLX_UGF_001",
        "Covalex Distribution Center S1DC02",
    ),
    ("Stanton1_DerelictSettlement_CuttersRig", "Cutter's Rig"),
    ("Stanton1_DerelictSettlement_FinnsFolly", "Finn's Folly"),
    ("Stanton1_DerelictSettlement_Ludlow", "Ludlow"),
    ("Stanton1_DerelictSettlement_MakersPoint", "Maker's Point"),
    ("Stanton1_DerelictSettlement_PickersField", "Picker's Field"),
    ("Stanton1_DerelictSettlement_Rappel", "Rappel"),
    ("Stanton1_DerelictSettlement_WeepingCove", "Weeping Cove"),
    ("Stanton1_DerelictSettlement_Zephyr", "Zephyr"),
    (
        "Stanton1_DistributionCenter_Covalex_01",
        "Covalex Distribution Centre S1DC06",
    ),
    (
        "Stanton1_DistributionCenter_Criminal_01",
        "Dupree Industrial Manufacturing Facility",
    ),
    (
        "Stanton1_DistributionCenter_Greycat_01",
        "Greycat Stanton I Production Complex-A",
    ),
    (
        "Stanton1_DistributionCenter_Greycat_02",
        "Greycat Stanton I Production Complex-B",
    ),
    ("Stanton1_DistributionCenter_Hurston_01", "HDPC-Farnesway"),
    ("Stanton1_DistributionCenter_Hurston_02", "HDPC-Cassillo"),
    (
        "Stanton1_DistributionCenter_Sakura_01",
        "Sakura Sun Magnolia Workcenter",
    ),
    ("Stanton1_DrugLab_001", "Echo Isle"),
    (
        "Stanton1_GRIN_UGF_001",
        "Greycat Stanton I Production Complex-A",
    ),
    (
        "Stanton1_GRIN_UGF_002",
        "Greycat Stanton I Production Complex-B",
    ),
    ("Stanton1_HRST_UGF_001", "HDPC-Cassillo"),
    ("Stanton1_HRST_UGF_002", "HDPC-Degland"),
    ("Stanton1_HRST_UGF_003", "HDPC-Farnesway"),
    ("Stanton1_HRST_UGF_004", "HDPC-Tiyago"),
    ("Stanton1_HurDynMining_001", "HDMS-Edmond"),
    ("Stanton1_HurDynMining_002", "HDMS-Oparei"),
    ("Stanton1_HurDynMining_003", "HDMS-Pinewood"),
    ("Stanton1_HurDynMining_004", "HDMS-Thedus"),
    ("Stanton1_HurDynMining_005", "HDMS-Hadley"),
    ("Stanton1_HurDynMining_006", "HDMS-Stanhope"),
    ("Stanton1_HurDynUGF_001", "HDSF-Adlai [CLOSED]"),
    ("Stanton1_HurDynUGF_002", "HDSF-Hendricks [CLOSED]"),
    ("Stanton1_HurDynUGF_003", "HDSF-Colfax"),
    ("Stanton1_HurDynUGF_004", "HDSF-Sherman"),
    ("Stanton1_HurDynUGF_005", "HDSF-Elbridge [CLOSED]"),
    ("Stanton1_HurDynUGF_006", "HDSF-Hobart [CLOSED]"),
    ("Stanton1_HurDynUGF_007", "HDSF-Millerand"),
    ("Stanton1_HurDynUGF_008", "HDSF-Tompkins"),
    ("Stanton1_HurDynUGF_009", "HDSF-Breckinridge [CLOSED]"),
    ("Stanton1_HurDynUGF_010", "HDSF-Zacharias [CLOSED]"),
    ("Stanton1_HurDynUGF_011", "HDSF-Rufus"),
    ("Stanton1_HurDynUGF_012", "HDSF-Tamar"),
    ("Stanton1_HurDynUGF_013", "HDSF-Ishmael [CLOSED]"),
    ("Stanton1_HurDynUGF_014", "HDSF-Damaris [CLOSED]"),
    ("Stanton1_HurDynUGF_015", "HDSF-Hiram"),
    ("Stanton1_HurDynUGF_016", "HDSF-Barnabas"),
    ("Stanton1_Hurston_Lorville_Hospital", "Maria Pure of Heart"),
    ("Stanton1_Hurston_Lorville_L19Residences", "L19 Residences"),
    ("Stanton1_L1", "HUR L1"),
    ("Stanton1_L1_01", "HUR L1-A"),
    ("Stanton1_L2", "HUR L2"),
    ("Stanton1_L2_01", "HUR L2-A"),
    ("Stanton1_L3", "HUR L3"),
    ("Stanton1_L3_01", "HUR L3-A"),
    ("Stanton1_L4", "HUR L4"),
    ("Stanton1_L4_01", "HUR L4-A"),
    ("Stanton1_L5", "HUR L5"),
    ("Stanton1_L5_01", "HUR L5-A"),
    ("Stanton1_Lorville", "Lorville"),
    ("Stanton1_Racetrack_LorvilleOutskirts", "Lorville Outskirts"),
    ("Stanton1_SalvageYard_001", "Reclamation & Disposal Orinth"),
    ("Stanton1_SecUGF_001", "HDRSO-Bramen"),
    ("Stanton1_SecUGF_002", "HDRSO-Walker"),
    ("Stanton1_SecUGF_003", "HDRSO-Brel"),
    ("Stanton1_SecUGF_004", "HDRSO-McKuen"),
    ("Stanton1_SecUGF_005", "HDRSO-Stott"),
    ("Stanton1_SecUGF_006", "HDRSO-Olliff"),
    ("Stanton1_SecUGF_007", "HDRSO-Franz"),
    ("Stanton1_SecUGF_008", "HDRSO-Malloy"),
    ("Stanton1_SecUGF_009", "HDRSO-Sheppard"),
    ("Stanton1_SecUGF_010", "HDRSO-Cronshaw"),
    ("Stanton1_SecUGF_011", "HDRSO-Pearce"),
    ("Stanton1_SecUGF_012", "HDRSO-Bowes"),
    ("Stanton1_SecUGF_013", "HDRSO-Foster"),
    ("Stanton1_SecUGF_014", "HDRSO-Giblin"),
    ("Stanton1_SecUGF_015", "HDRSO-Tillman"),
    ("Stanton1_SecUGF_016", "HDRSO-Marling"),
    ("Stanton1_SecUGF_017", "HDRSO-Sims"),
    ("Stanton1_SecUGF_018", "HDRSO-Baier"),
    ("Stanton1_SecUGF_019", "HDRSO-Wyatt"),
    ("Stanton1_SecUGF_020", "HDRSO-Bardie"),
    ("Stanton1_SecUGF_021", "HDRSO-Newman"),
    ("Stanton1_SecUGF_022", "HDRSO-Hosley"),
    ("Stanton1_SecUGF_023", "HDRSO-Bersch"),
    ("Stanton1_Transfer", "Everus Harbor"),
    ("Stanton1_Transfer_clinic", "Everus Harbor Clinic"),
    ("Stanton1_UGF_secdep_name", "HDOF-Palomar"),
    ("Stanton1a", "Arial"),
    ("Stanton1a_ASD_Delving_Facility_001", "Onyx Facility S1A1"),
    ("Stanton1a_ASD_Delving_Facility_002", "Onyx Facility S1A2"),
    ("Stanton1a_ASD_Delving_Facility_003", "Onyx Facility S1A3"),
    ("Stanton1a_ASD_Delving_Facility_004", "Onyx Facility S1A4"),
    ("Stanton1a_ASD_Delving_Facility_005", "Onyx Facility S1A5"),
    ("Stanton1a_ASD_Delving_Facility_006", "Onyx Facility S1A6"),
    ("Stanton1a_ASD_Delving_Facility_007", "Onyx Facility S1A7"),
    ("Stanton1a_ASD_Delving_Facility_008", "Onyx Facility S1A8"),
    ("Stanton1a_ASD_Delving_Facility_009", "Onyx Facility S1A9"),
    ("Stanton1a_ASD_Delving_Facility_010", "Onyx Facility S1A10"),
    ("Stanton1a_HurDynMining_001", "HDMS-Bezdek"),
    ("Stanton1a_HurDynMining_002", "HDMS-Lathan"),
    ("Stanton1b", "Aberdeen"),
    ("Stanton1b_Aberdeen_Location", "Aberdeen, Stanton System"),
    (
        "Stanton1b_Aberdeen_Prison",
        "Klescher Rehabilitation Facility",
    ),
    ("Stanton1b_ASD_Delving_Facility_001", "Onyx Facility S1B1"),
    ("Stanton1b_ASD_Delving_Facility_002", "Onyx Facility S1B2"),
    ("Stanton1b_ASD_Delving_Facility_003", "Onyx Facility S1B3"),
    ("Stanton1b_ASD_Delving_Facility_004", "Onyx Facility S1B4"),
    ("Stanton1b_ASD_Delving_Facility_005", "Onyx Facility S1B5"),
    ("Stanton1b_ASD_Delving_Facility_006", "Onyx Facility S1B6"),
    ("Stanton1b_ASD_Delving_Facility_007", "Onyx Facility S1B7"),
    ("Stanton1b_ASD_Delving_Facility_008", "Onyx Facility S1B8"),
    ("Stanton1b_ASD_Delving_Facility_009", "Onyx Facility S1B9"),
    ("Stanton1b_ASD_Delving_Facility_010", "Onyx Facility S1B10"),
    ("Stanton1b_Cave_Aband_01", "HDES-Dobbs (NA)"),
    ("Stanton1b_EMShelter_Prison", "Barton Flats Aid Shelter"),
    ("Stanton1b_HurDynMining_001", "HDMS-Norgaard"),
    ("Stanton1b_HurDynMining_002", "HDMS-Anderson"),
    (
        "Stanton1b_MiningCompound_drlct_001_a",
        "Sloane Mining Compound-A",
    ),
    (
        "Stanton1b_MiningCompound_drlct_001_b",
        "Sloane Mining Compound-B",
    ),
    (
        "Stanton1b_MiningCompound_drlct_001_c",
        "Sloane Mining Compound-C",
    ),
    (
        "Stanton1b_MiningCompound_drlct_001_d",
        "Sloane Mining Compound-D",
    ),
    (
        "Stanton1b_MiningCompound_drlct_002_a",
        "Reyes Mining Compound-A",
    ),
    (
        "Stanton1b_MiningCompound_drlct_002_b",
        "Reyes Mining Compound-B",
    ),
    (
        "Stanton1b_MiningCompound_drlct_002_c",
        "Reyes Mining Compound-C",
    ),
    (
        "Stanton1b_MiningCompound_drlct_002_d",
        "Reyes Mining Compound-D",
    ),
    ("Stanton1b_OLP_001", "Ruptura OLP"),
    ("Stanton1b_OLP_002", "Vivere OLP"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_1-1", "Ruptura PAF-I"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_1-2", "Ruptura PAF-II"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_1-3", "Ruptura PAF-III"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_2-1", "Vivere PAF-I"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_2-2", "Vivere PAF-II"),
    ("Stanton1b_Outpost_col_m_drlct_PAF_2-3", "Vivere PAF-III"),
    ("Stanton1c", "Magda"),
    ("Stanton1c_ASD_Delving_Facility_001", "Onyx Facility S1C1"),
    ("Stanton1c_ASD_Delving_Facility_002", "Onyx Facility S1C2"),
    ("Stanton1c_ASD_Delving_Facility_003", "Onyx Facility S1C3"),
    ("Stanton1c_ASD_Delving_Facility_004", "Onyx Facility S1C4"),
    ("Stanton1c_ASD_Delving_Facility_005", "Onyx Facility S1C5"),
    ("Stanton1c_ASD_Delving_Facility_006", "Onyx Facility S1C6"),
    ("Stanton1c_ASD_Delving_Facility_007", "Onyx Facility S1C7"),
    ("Stanton1c_ASD_Delving_Facility_008", "Onyx Facility S1C8"),
    ("Stanton1c_ASD_Delving_Facility_009", "Onyx Facility S1C9"),
    ("Stanton1c_ASD_Delving_Facility_010", "Onyx Facility S1C10"),
    ("Stanton1c_HurDynMining_001", "HDMS-Hahn"),
    ("Stanton1c_HurDynMining_002", "HDMS-Perlman"),
    ("Stanton1d", "Ita"),
    ("Stanton1d_ASD_Delving_Facility_001", "Onyx Facility S1D1"),
    ("Stanton1d_ASD_Delving_Facility_002", "Onyx Facility S1D2"),
    ("Stanton1d_ASD_Delving_Facility_003", "Onyx Facility S1D3"),
    ("Stanton1d_ASD_Delving_Facility_004", "Onyx Facility S1D4"),
    ("Stanton1d_ASD_Delving_Facility_005", "Onyx Facility S1D5"),
    ("Stanton1d_ASD_Delving_Facility_006", "Onyx Facility S1D6"),
    ("Stanton1d_ASD_Delving_Facility_007", "Onyx Facility S1D7"),
    ("Stanton1d_ASD_Delving_Facility_008", "Onyx Facility S1D8"),
    ("Stanton1d_ASD_Delving_Facility_009", "Onyx Facility S1D9"),
    ("Stanton1d_ASD_Delving_Facility_010", "Onyx Facility S1D10"),
    ("Stanton1d_HurDynMining_001", "HDMS-Woodruff"),
    ("Stanton1d_HurDynMining_002", "HDMS-Ryder"),
    ("Stanton2", "Crusader"),
    ("Stanton2_AdminCenter", "Admin Center"),
    ("Stanton2_BrushwoodPlatform", "Brushwood"),
    ("Stanton2_CloudrestRetreatCluster", "Cloudrest Retreat"),
    ("Stanton2_CommArray_001", "Comm Array ST2-55"),
    ("Stanton2_CommArray_002", "Comm Array ST2-28"),
    ("Stanton2_CommArray_003", "Comm Array ST2-47"),
    ("Stanton2_CommArray_004", "Comm Array ST2-76"),
    ("Stanton2_Courier_Org", "Stanton2_Courier_Org"),
    ("Stanton2_EmpyreanParkCluster", "Empyrean Park"),
    ("Stanton2_HartmoorePlatform", "Hartmoore"),
    ("Stanton2_L1", "CRU L1"),
    ("Stanton2_L1_01", "CRU L1-A"),
    ("Stanton2_L2", "CRU L2"),
    ("Stanton2_L2_01", "CRU L2-A"),
    ("Stanton2_L2_02", "CRU L2-B"),
    ("Stanton2_L2_03", "CRU L2-C"),
    ("Stanton2_L3", "CRU L3"),
    ("Stanton2_L3_01", "CRU L3-A"),
    ("Stanton2_L4", "CRU L4"),
    ("Stanton2_L4_01", "CRU L4-A"),
    ("Stanton2_L5", "CRU L5"),
    ("Stanton2_L5_01", "CRU L5-A"),
    ("Stanton2_Orison", "Orison"),
    ("Stanton2_Orison_Hospital", "Orison General"),
    ("Stanton2_ProspectPointCluster", "Prospect Point"),
    ("Stanton2_Racetrack_CaplanCircuit", "Caplan Circuit"),
    ("Stanton2_SolankiPlatform", "Solanki"),
    ("Stanton2_Transfer_Seraphim", "Seraphim Station"),
    ("Stanton2_Transfer_Seraphim_clinic", "Seraphim Clinic"),
    ("Stanton2a", "Cellin"),
    ("Stanton2a_ASD_Delving_Facility_001", "Onyx Facility S2A1"),
    ("Stanton2a_ASD_Delving_Facility_002", "Onyx Facility S2A2"),
    ("Stanton2a_ASD_Delving_Facility_003", "Onyx Facility S2A3"),
    ("Stanton2a_ASD_Delving_Facility_004", "Onyx Facility S2A4"),
    ("Stanton2a_ASD_Delving_Facility_005", "Onyx Facility S2A5"),
    ("Stanton2a_ASD_Delving_Facility_006", "Onyx Facility S2A6"),
    ("Stanton2a_ASD_Delving_Facility_007", "Onyx Facility S2A7"),
    ("Stanton2a_ASD_Delving_Facility_008", "Onyx Facility S2A8"),
    ("Stanton2a_ASD_Delving_Facility_009", "Onyx Facility S2A9"),
    ("Stanton2a_ASD_Delving_Facility_010", "Onyx Facility S2A10"),
    ("Stanton2a_DrugUGF_001", "NT-999-XV"),
    ("Stanton2a_EMShelter_001", "Julep Ravine Aid Shelter"),
    ("Stanton2a_EMShelter_002", "Flanagan's Ravine Aid Shelter"),
    ("Stanton2a_EMShelter_003", "Ashburn Channel Aid Shelter"),
    ("Stanton2a_EMShelter_004", "Mogote Aid Shelter"),
    ("Stanton2a_IndyFarmer_001", "Gallete Family Farms"),
    ("Stanton2a_IndyMine_001", "Tram & Myers Mining"),
    ("Stanton2a_Rayari_001", "Hickes Research Outpost"),
    ("Stanton2a_SecUGF_001", "Security Post Dipur"),
    ("Stanton2a_SecUGF_002", "Security Post Lespin"),
    ("Stanton2a_SecUGF_003", "Security Post Criska"),
    ("Stanton2a_SecUGF_004", "Security Post Birbari"),
    ("Stanton2a_SecUGF_005", "Security Post Chilad"),
    ("Stanton2a_SecUGF_006", "Security Post Saktigar"),
    ("Stanton2a_SecUGF_007", "Security Post Pakote"),
    ("Stanton2a_SecUGF_008", "Security Post Awala"),
    ("Stanton2a_SecUGF_009", "Security Post Kota"),
    ("Stanton2a_SecUGF_010", "Security Post Sharga"),
    ("Stanton2a_SecUGF_011", "Security Post Gandan"),
    ("Stanton2a_Stash_001", "PRIVATE PROPERTY"),
    ("Stanton2a_TerraMills_001", "Terra Mills HydroFarm"),
    ("Stanton2b", "Daymar"),
    ("Stanton2b_600iSettlement", "Whistler's Crypt"),
    ("Stanton2b_ArcCorp_001", "ArcCorp Mining Area 141"),
    ("Stanton2b_ASD_Delving_Facility_001", "Onyx Facility S2B1"),
    ("Stanton2b_ASD_Delving_Facility_002", "Onyx Facility S2B2"),
    ("Stanton2b_ASD_Delving_Facility_003", "Onyx Facility S2B3"),
    ("Stanton2b_ASD_Delving_Facility_004", "Onyx Facility S2B4"),
    ("Stanton2b_ASD_Delving_Facility_005", "Onyx Facility S2B5"),
    ("Stanton2b_ASD_Delving_Facility_006", "Onyx Facility S2B6"),
    ("Stanton2b_ASD_Delving_Facility_007", "Onyx Facility S2B7"),
    ("Stanton2b_ASD_Delving_Facility_008", "Onyx Facility S2B8"),
    ("Stanton2b_ASD_Delving_Facility_009", "Onyx Facility S2B9"),
    ("Stanton2b_ASD_Delving_Facility_010", "Onyx Facility S2B10"),
    ("Stanton2b_Cave_Aband_01", "Kudre Ore Mine (Closed)"),
    (
        "Stanton2b_CRUS_UGF_001",
        "Crusader Industries Daymar Center B14",
    ),
    ("Stanton2b_DrugUGF_001", "NT-999-XVI"),
    ("Stanton2b_DrugUGF_002", "The Garden"),
    ("Stanton2b_DrugUGF_003", "TPF"),
    ("Stanton2b_EMShelter_001", "Tamdon Plains Aid Shelter"),
    ("Stanton2b_EMShelter_002", "Eager Flats Aid Shelter"),
    ("Stanton2b_EMShelter_003", "Dunlow Ridge Aid Shelter"),
    ("Stanton2b_EMShelter_004", "Wolf Point Aid Shelter"),
    ("Stanton2b_IndyFarmer_001", "Bountiful Harvest Hydroponics"),
    ("Stanton2b_IndyMine_001", "Kudre Ore"),
    (
        "Stanton2b_MiningCompound_drlct_001_a",
        "Baud Mining Compound-A",
    ),
    (
        "Stanton2b_MiningCompound_drlct_001_b",
        "Baud Mining Compound-B",
    ),
    (
        "Stanton2b_MiningCompound_drlct_001_c",
        "Baud Mining Compound-C",
    ),
    (
        "Stanton2b_MiningCompound_drlct_001_d",
        "Baud Mining Compound-D",
    ),
    (
        "Stanton2b_MiningCompound_drlct_002_a",
        "Gaffney Mining Compound-A",
    ),
    (
        "Stanton2b_MiningCompound_drlct_002_b",
        "Gaffney Mining Compound-B",
    ),
    (
        "Stanton2b_MiningCompound_drlct_002_c",
        "Gaffney Mining Compound-C",
    ),
    (
        "Stanton2b_MiningCompound_drlct_002_d",
        "Gaffney Mining Compound-D",
    ),
    ("Stanton2b_OLP_001", "Lamina OLP"),
    ("Stanton2b_OLP_002", "Attritus OLP"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_1-1", "Lamina PAF-I"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_1-2", "Lamina PAF-II"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_1-3", "Lamina PAF-III"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_2-1", "Attritus PAF-I"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_2-2", "Attritus PAF-II"),
    ("Stanton2b_Outpost_col_m_drlct_PAF_2-3", "Attritus PAF-III"),
    ("Stanton2b_Racetrack_YadarValley", "Yadar Valley"),
    ("Stanton2b_SalvageYard_001", "Brio's Breaker Yard"),
    ("Stanton2b_SecUGF_001", "Security Post Thaquray"),
    ("Stanton2b_SecUGF_002", "Security Post Moluto"),
    ("Stanton2b_SecUGF_003", "Security Post Prashad"),
    ("Stanton2b_SecUGF_004", "Security Post Tavan"),
    ("Stanton2b_SecUGF_005", "Security Post Ulaga"),
    ("Stanton2b_SecUGF_006", "Security Post Dawu"),
    ("Stanton2b_SecUGF_007", "Security Post Menian"),
    ("Stanton2b_SecUGF_008", "Security Post Yafa"),
    ("Stanton2b_SecUGF_009", "Security Post Erden"),
    ("Stanton2b_SecUGF_010", "Security Post Reawick"),
    ("Stanton2b_Shubin_001", "Shubin Mining Facility SCD-1"),
    ("Stanton2b_Stash_001", "Nuen Waste Management"),
    ("Stanton2c", "Yela"),
    ("Stanton2c_ArcCorp_001", "ArcCorp Mining Area 157"),
    ("Stanton2c_ASD_Delving_Facility_001", "Onyx Facility S2C1"),
    ("Stanton2c_ASD_Delving_Facility_002", "Onyx Facility S2C2"),
    ("Stanton2c_ASD_Delving_Facility_003", "Onyx Facility S2C3"),
    ("Stanton2c_ASD_Delving_Facility_004", "Onyx Facility S2C4"),
    ("Stanton2c_ASD_Delving_Facility_005", "Onyx Facility S2C5"),
    ("Stanton2c_ASD_Delving_Facility_006", "Onyx Facility S2C6"),
    ("Stanton2c_ASD_Delving_Facility_007", "Onyx Facility S2C7"),
    ("Stanton2c_ASD_Delving_Facility_008", "Onyx Facility S2C8"),
    ("Stanton2c_ASD_Delving_Facility_009", "Onyx Facility S2C9"),
    ("Stanton2c_ASD_Delving_Facility_010", "Onyx Facility S2C10"),
    ("Stanton2c_DrugLab_001", "Jumptown"),
    ("Stanton2c_DrugUGF_001", "NT-999-XXII"),
    ("Stanton2c_DrugUGF_002", "Utopia"),
    ("Stanton2c_DrugUGF_003", "Connor's"),
    ("Stanton2c_DrugUGF_004", "Afterlife"),
    ("Stanton2c_EMShelter_001", "Aston Ridge Aid Shelter"),
    ("Stanton2c_EMShelter_002", "Kosso Basin Aid Shelter"),
    ("Stanton2c_EMShelter_003", "Nakamura Valley Aid Shelter"),
    ("Stanton2c_EMShelter_004", "Talarine Divide Aid Shelter"),
    ("Stanton2c_IndyMine_001", "Benson Mining Outpost"),
    ("Stanton2c_Racetrack_MinersLament", "Miner's Lament"),
    ("Stanton2c_Rayari_001", "Deakins Research Outpost"),
    ("Stanton2c_SecUGF_001", "Security Post Opal"),
    ("Stanton2c_SecUGF_002", "Security Post Wan"),
    ("Stanton2c_SecUGF_003", "Security Post Hasik"),
    ("Stanton2c_SecUGF_004", "Security Post Peska"),
    ("Stanton2c_SecUGF_005", "Security Post Iteke"),
    ("Stanton2c_SecUGF_006", "Security Post Walvis"),
    ("Stanton2c_SecUGF_007", "Security Post Klipra"),
    ("Stanton2c_SecUGF_008", "Security Post Moka"),
    ("Stanton2c_SecUGF_009", "Security Post Triolet"),
    ("Stanton2c_Stash_001", "NT-999-XX"),
    ("Stanton3", "ArcCorp"),
    ("Stanton3_ArcCorp_Area04", "Area04"),
    ("Stanton3_ArcCorp_Area06", "Area06"),
    ("Stanton3_ArcCorp_Area11", "Area11"),
    ("Stanton3_ArcCorp_Area17", "Area17"),
    ("Stanton3_ArcCorp_Area20", "Area20"),
    ("Stanton3_ArcCorp_Habs_AdiraFalls", "Adira Falls Apartments"),
    ("Stanton3_Area18", "Area18"),
    ("Stanton3_Area18_Central", "Area18 Central"),
    (
        "Stanton3_Area18_Hospital",
        "Empire Health Services Medstation",
    ),
    ("Stanton3_Area18_Plaza", "Plaza"),
    ("Stanton3_CommArray_001", "Comm Array ST3-90"),
    ("Stanton3_CommArray_002", "Comm Array ST3-18"),
    ("Stanton3_CommArray_003", "Comm Array ST3-35"),
    ("Stanton3_Courier_Org", "Stanton3_Courier_Org"),
    ("Stanton3_L1", "ARC L1"),
    ("Stanton3_L1_01", "ARC L1-A"),
    ("Stanton3_L2", "ARC L2"),
    ("Stanton3_L2_01", "ARC L2-A"),
    ("Stanton3_L3", "ARC L3"),
    ("Stanton3_L3_01", "ARC L3-A"),
    ("Stanton3_L4", "ARC L4"),
    ("Stanton3_L4_01", "ARC L4-A"),
    ("Stanton3_L5", "ARC L5"),
    ("Stanton3_L5_01", "ARC L5-A"),
    ("Stanton3_OrbitalRelay", "Orbital Relay AC-421"),
    ("Stanton3_Racetrack_SkyScraper", "The Sky Scraper"),
    ("Stanton3_Transfer", "Baijini Point"),
    ("Stanton3_Transfer_clinic", "Baijini Point Clinic"),
    ("Stanton3a", "Lyria"),
    ("Stanton3a_ASD_Delving_Facility_001", "Onyx Facility S3A1"),
    ("Stanton3a_ASD_Delving_Facility_002", "Onyx Facility S3A2"),
    ("Stanton3a_ASD_Delving_Facility_003", "Onyx Facility S3A3"),
    ("Stanton3a_ASD_Delving_Facility_004", "Onyx Facility S3A4"),
    ("Stanton3a_ASD_Delving_Facility_005", "Onyx Facility S3A5"),
    ("Stanton3a_ASD_Delving_Facility_006", "Onyx Facility S3A6"),
    ("Stanton3a_ASD_Delving_Facility_007", "Onyx Facility S3A7"),
    ("Stanton3a_ASD_Delving_Facility_008", "Onyx Facility S3A8"),
    ("Stanton3a_ASD_Delving_Facility_009", "Onyx Facility S3A9"),
    ("Stanton3a_ASD_Delving_Facility_010", "Onyx Facility S3A10"),
    ("Stanton3a_DrugLab_001", "Paradise Cove"),
    ("Stanton3a_DrugUGF_001", "Launch Pad"),
    ("Stanton3a_DrugUGF_002", "Buckets"),
    (
        "Stanton3a_GRIN_UGF_001",
        "Greycat Stanton 3a Production Complex-A",
    ),
    ("Stanton3a_IndyMine_001", "Humboldt Mines"),
    ("Stanton3a_IndyMine_002", "Loveridge Mineral Reserve"),
    ("Stanton3a_SecUGF_001", "ArcCorp Security Post 011"),
    ("Stanton3a_SecUGF_002", "ArcCorp Security Post 017"),
    ("Stanton3a_SecUGF_003", "ArcCorp Security Post 024"),
    ("Stanton3a_SecUGF_004", "ArcCorp Security Post 029"),
    ("Stanton3a_SecUGF_005", "ArcCorp Security Post 033"),
    ("Stanton3a_SecUGF_006", "ArcCorp Security Post 038"),
    ("Stanton3a_SecUGF_007", "ArcCorp Security Post 042"),
    ("Stanton3a_SecUGF_008", "ArcCorp Security Post 045"),
    ("Stanton3a_SecUGF_009", "ArcCorp Security Post 052"),
    ("Stanton3a_SecUGF_010", "ArcCorp Security Post 059"),
    ("Stanton3a_SecUGF_011", "ArcCorp Security Post 060"),
    ("Stanton3a_Shubin_001", "Shubin Mining Facility SAL-2"),
    ("Stanton3a_Shubin_002", "Shubin Mining Facility SAL-5"),
    ("Stanton3a_Stash_001", "The Orphanage"),
    ("Stanton3a_UFG_006", "Shubin Processing Facility SPAL-7"),
    ("Stanton3a_UFG_007", "Shubin Processing Facility SPAL-9"),
    ("Stanton3a_UFG_008", "Shubin Processing Facility SPAL-12"),
    ("Stanton3a_UGF_001", "The Pit"),
    ("Stanton3a_UGF_002", "Wheeler's"),
    ("Stanton3a_UGF_003", "Teddy's Playhouse"),
    ("Stanton3a_UGF_004", "Elsewhere"),
    ("Stanton3a_UGF_005", "Shubin Processing Facility SPAL-3"),
    ("Stanton3a_UGF_009", "Operations Depot Lyria-1"),
    ("Stanton3a_UGF_010", "Shubin Processing Facility SPAL-16"),
    ("Stanton3a_UGF_011", "Shubin Processing Facility SPAL-21"),
    ("Stanton3b", "Wala"),
    ("Stanton3b_ARCC_UGF_001", "ArcCorp Wala-1 Industrial Park"),
    ("Stanton3b_ArcCorp_001", "ArcCorp Mining Area 045"),
    ("Stanton3b_ArcCorp_002", "ArcCorp Mining Area 048"),
    ("Stanton3b_ArcCorp_003", "ArcCorp Mining Area 056"),
    ("Stanton3b_ArcCorp_004", "ArcCorp Mining Area 061"),
    ("Stanton3b_ASD_Delving_Facility_001", "Onyx Facility S3B1"),
    ("Stanton3b_ASD_Delving_Facility_002", "Onyx Facility S3B2"),
    ("Stanton3b_ASD_Delving_Facility_003", "Onyx Facility S3B3"),
    ("Stanton3b_ASD_Delving_Facility_004", "Onyx Facility S3B4"),
    ("Stanton3b_ASD_Delving_Facility_005", "Onyx Facility S3B5"),
    ("Stanton3b_ASD_Delving_Facility_006", "Onyx Facility S3B6"),
    ("Stanton3b_ASD_Delving_Facility_007", "Onyx Facility S3B7"),
    ("Stanton3b_ASD_Delving_Facility_008", "Onyx Facility S3B8"),
    ("Stanton3b_ASD_Delving_Facility_009", "Onyx Facility S3B9"),
    ("Stanton3b_ASD_Delving_Facility_010", "Onyx Facility S3B10"),
    ("Stanton3b_DrugUGF_001", "Lost and Found"),
    ("Stanton3b_DrugUGF_002", "Good Times Temple"),
    ("Stanton3b_IndyFarmer_001", "Shady Glen Farms"),
    ("Stanton3b_SalvageYard_001", "Samson & Son's Salvage Center"),
    ("Stanton3b_SecUGF_001", "ArcCorp Security Post 066"),
    ("Stanton3b_SecUGF_002", "ArcCorp Security Post 074"),
    ("Stanton3b_SecUGF_003", "ArcCorp Security Post 078"),
    ("Stanton3b_SecUGF_004", "ArcCorp Security Post 087"),
    ("Stanton3b_SecUGF_005", "ArcCorp Security Post 089"),
    ("Stanton3b_SecUGF_006", "ArcCorp Security Post 092"),
    ("Stanton3b_SecUGF_007", "ArcCorp Security Post 094"),
    ("Stanton3b_SecUGF_008", "ArcCorp Security Post 101"),
    ("Stanton3b_SecUGF_009", "ArcCorp Security Post 108"),
    ("Stanton3b_SecUGF_010", "ArcCorp Security Post 111"),
    ("Stanton3b_UGF_001", "ArcCorp Processing Center 115"),
    ("Stanton3b_UGF_002", "ArcCorp Processing Center 123"),
    ("Stanton4", "microTech"),
    ("Stanton4_CommArray_001", "Comm Array ST4-22"),
    ("Stanton4_CommArray_002", "Comm Array ST4-31"),
    ("Stanton4_CommArray_003", "Comm Array ST4-59"),
    ("Stanton4_CommArray_004", "Comm Array ST4-64"),
    ("Stanton4_Courier_Org", "Stanton4_Courier_Org"),
    ("Stanton4_CRAS_UGF_001", "Cry-Astro Processing Plant 34-12"),
    (
        "Stanton4_CVLX_UGF_001",
        "Covalex Distribution Center S4DC05",
    ),
    (
        "Stanton4_DerelictSettlement_AstorsClearing",
        "Astor's Clearing",
    ),
    (
        "Stanton4_DerelictSettlement_BloodshotRidge",
        "Bloodshot Ridge",
    ),
    ("Stanton4_DerelictSettlement_Dunboro", "Dunboro"),
    ("Stanton4_DerelictSettlement_Frostbite", "Frostbite"),
    ("Stanton4_DerelictSettlement_HarpersPoint", "Harper's Point"),
    (
        "Stanton4_DerelictSettlement_MorelandHills",
        "Moreland Hills",
    ),
    ("Stanton4_DerelictSettlement_RazorsEdge", "Razor's Edge"),
    (
        "Stanton4_DistributionCenter_Covalex_01",
        "Covalex Distribution Centre S4DC05",
    ),
    (
        "Stanton4_DistributionCenter_CryAstro_01",
        "Cry-Astro Processing Plant 34-12",
    ),
    (
        "Stanton4_DistributionCenter_CryAstro_02",
        "Cry-Astro Processing Plant 19-02",
    ),
    (
        "Stanton4_DistributionCenter_Greycat_01",
        "Greycat Stanton IV Production Complex-A",
    ),
    (
        "Stanton4_DistributionCenter_microTech_01",
        "microTech Logistics Depot S4LD01",
    ),
    (
        "Stanton4_DistributionCenter_microTech_02",
        "microTech Logistics Depot S4LD13",
    ),
    (
        "Stanton4_DistributionCenter_Sakura_01",
        "Sakura Sun Goldenrod Workcenter",
    ),
    ("Stanton4_EMShelter_001", "Calhoun Pass Emergency Shelter"),
    ("Stanton4_EMShelter_002", "Point Wain Emergency Shelter"),
    ("Stanton4_EMShelter_003", "Nuiqsut Emergency Shelter"),
    ("Stanton4_EMShelter_004", "Clear View Emergency Shelter"),
    ("Stanton4_L1", "MIC L1"),
    ("Stanton4_L1_01", "MIC L1-A"),
    ("Stanton4_L1_02", "MIC L1-B"),
    ("Stanton4_L1_NavyStation_NAME", "INS Jericho"),
    ("Stanton4_L2", "MIC L2"),
    ("Stanton4_L2_01", "MIC L2-A"),
    ("Stanton4_L2_02", "MIC L2-B"),
    ("Stanton4_L2_03", "MIC L2-C"),
    ("Stanton4_L3", "MIC L3"),
    ("Stanton4_L3_01", "MIC L3-A"),
    ("Stanton4_L4", "MIC L4"),
    ("Stanton4_L4_01", "MIC L4-A"),
    ("Stanton4_L5", "MIC L5"),
    ("Stanton4_L5_01", "MIC L5-A"),
    ("Stanton4_L5_02", "MIC L5-B"),
    ("Stanton4_MITE_UGF_001", "microTech Logistics Depot S4LD01"),
    ("Stanton4_NewBab_AspireGrand", "Aspire Grand"),
    (
        "Stanton4_NewBab_DomeSurfaceExit",
        "The Commons Surface Exit",
    ),
    (
        "Stanton4_NewBab_DomeSurfaceExit_GroundATC",
        "The Commons Parking",
    ),
    ("Stanton4_NewBab_Hospital", "Brentworth Care Center"),
    ("Stanton4_NewBab_MetroLoop", "MT MetroLoop"),
    ("Stanton4_NewBab_NBIS", "NBIS Terminal"),
    ("Stanton4_NewBab_NBIS_ATC", "NB Int. Spaceport"),
    ("Stanton4_NewBab_NBIS_GroundATC", "NBIS Parking"),
    ("Stanton4_NewBab_PlanetaryServices", "MT Planetary Services"),
    (
        "Stanton4_NewBab_PlanetarySurfaceExit",
        "Planetary Surface Exit",
    ),
    ("Stanton4_NewBab_TheCommons", "The Commons"),
    ("Stanton4_NewBabbage", "New Babbage"),
    ("Stanton4_Rayari_001", "Rayari Deltana Research Outpost"),
    ("Stanton4_Rayari_002", "Rayari Livengood Research Outpost"),
    ("Stanton4_ReclaimerSettlement", "Ghost Hollow"),
    ("Stanton4_SASU_UGF_001", "Sakura Sun Goldenrod Workcenter"),
    ("Stanton4_SecUGF_001", "MT SecurityCenter BH5-KEH-6"),
    ("Stanton4_SecUGF_002", "MT SecurityCenter 9PL-Q42-K"),
    ("Stanton4_SecUGF_003", "MT SecurityCenter GSW-NM3-E"),
    ("Stanton4_SecUGF_004", "MT SecurityCenter XGT-33W-7"),
    ("Stanton4_SecUGF_005", "MT SecurityCenter E6C-BRT-M"),
    ("Stanton4_SecUGF_006", "MT SecurityCenter UDB-Z4W-2"),
    ("Stanton4_SecUGF_007", "MT SecurityCenter DRC-F2S-6"),
    ("Stanton4_SecUGF_008", "MT SecurityCenter 9WB-HV7-P"),
    ("Stanton4_SecUGF_009", "MT SecurityCenter OEE-5RG-5"),
    ("Stanton4_SecUGF_010", "MT SecurityCenter SLP-VC3-W"),
    ("Stanton4_SecUGF_011", "MT SecurityCenter D66-CRW-F"),
    ("Stanton4_SecUGF_012", "MT SecurityCenter 4HJ-LVE-A"),
    ("Stanton4_Shubin_001", "Shubin Mining Facility SM0-13"),
    ("Stanton4_Shubin_002", "Shubin Mining Facility SM0-22"),
    ("Stanton4_Shubin_003", "Shubin Mining Facility SM0-18"),
    ("Stanton4_Shubin_004", "Shubin Mining Facility SM0-10"),
    ("Stanton4_Stash_001", "The Necropolis"),
    ("Stanton4_Stash_002", "Outpost 54"),
    ("Stanton4_Transfer", "Port Tressler"),
    ("Stanton4_Transfer_clinic", "Port Tressler Clinic"),
    ("Stanton4_UGF_001", "MT DataCenter 5WQ-R2V-C (Offline)"),
    ("Stanton4_UGF_002", "MT DataCenter 2UB-RB9-5"),
    ("Stanton4_UGF_003", "MT DataCenter 8FK-Q2X-K"),
    ("Stanton4_UGF_004", "MT DataCenter E2Q-NSG-Y (Offline)"),
    ("Stanton4_UGF_005", "MT OpCenter TLI-4"),
    ("Stanton4_UGF_006", "MT DataCenter D79-ECG-R (Offline)"),
    ("Stanton4_UGF_007", "MT DataCenter QVX-J88-J"),
    ("Stanton4_UGF_008", "MT DataCenter TMG-XEV-2"),
    ("Stanton4_UGF_009", "MT DataCenter KH3-AAE-L"),
    ("Stanton4_UGF_010", "MT DataCenter L8P-JUC-8 (Offline)"),
    ("Stanton4_UGF_011", "MT DataCenter 4HJ-LVE-A"),
    ("Stanton4a", "Calliope"),
    ("Stanton4a_ASD_Delving_Facility_001", "Onyx Facility S4A1"),
    ("Stanton4a_ASD_Delving_Facility_002", "Onyx Facility S4A2"),
    ("Stanton4a_ASD_Delving_Facility_003", "Onyx Facility S4A3"),
    ("Stanton4a_ASD_Delving_Facility_004", "Onyx Facility S4A4"),
    ("Stanton4a_ASD_Delving_Facility_005", "Onyx Facility S4A5"),
    ("Stanton4a_ASD_Delving_Facility_006", "Onyx Facility S4A6"),
    ("Stanton4a_ASD_Delving_Facility_007", "Onyx Facility S4A7"),
    ("Stanton4a_ASD_Delving_Facility_008", "Onyx Facility S4A8"),
    ("Stanton4a_ASD_Delving_Facility_009", "Onyx Facility S4A9"),
    ("Stanton4a_ASD_Delving_Facility_010", "Onyx Facility S4A10"),
    ("Stanton4a_DrugLab_001", "Raven's Roost"),
    ("Stanton4a_Rayari_001", "Rayari Kaltag Research Outpost"),
    ("Stanton4a_Rayari_002", "Rayari Anvik Research Outpost"),
    ("Stanton4a_SecUGF_001", "MT SecurityCenter VD9-87R-P"),
    ("Stanton4a_SecUGF_002", "MT SecurityCenter 6EE-GVH-9"),
    ("Stanton4a_SecUGF_003", "MT SecurityCenter PLM-9YW-Q"),
    ("Stanton4a_SecUGF_004", "MT SecurityCenter CTB-B3U-1"),
    ("Stanton4a_SecUGF_005", "MT SecurityCenter DXC-25G-L"),
    ("Stanton4a_SecUGF_006", "MT SecurityCenter KWS-GPZ-5"),
    ("Stanton4a_SecUGF_007", "MT SecurityCenter JWB-D9L-4"),
    ("Stanton4a_SecUGF_008", "MT SecurityCenter H36-YBG-R"),
    ("Stanton4a_SecUGF_009", "MT SecurityCenter FQ5-URX-8"),
    ("Stanton4a_Shubin_001", "Shubin Mining Facility SMCa-6"),
    ("Stanton4a_Shubin_002", "Shubin Mining Facility SMCa-8"),
    (
        "Stanton4a_UGF_001",
        "Shubin Processing Facility SPMC-3 [CLOSED]",
    ),
    (
        "Stanton4a_UGF_002",
        "Shubin Processing Facility SPMC-5 [CLOSED]",
    ),
    ("Stanton4a_UGF_003", "Shubin Processing Facility SPMC-10"),
    (
        "Stanton4a_UGF_004",
        "Shubin Processing Facility SPMC-11 [CLOSED]",
    ),
    (
        "Stanton4a_UGF_005",
        "Shubin Processing Facility SPMC-14 [CLOSED]",
    ),
    ("Stanton4a_UGF_006", "Shubin Processing Facility SPMC-1"),
    ("Stanton4b", "Clio"),
    ("Stanton4b_ASD_Delving_Facility_001", "Onyx Facility S4B1"),
    ("Stanton4b_ASD_Delving_Facility_002", "Onyx Facility S4B2"),
    ("Stanton4b_ASD_Delving_Facility_003", "Onyx Facility S4B3"),
    ("Stanton4b_ASD_Delving_Facility_004", "Onyx Facility S4B4"),
    ("Stanton4b_ASD_Delving_Facility_005", "Onyx Facility S4B5"),
    ("Stanton4b_ASD_Delving_Facility_006", "Onyx Facility S4B6"),
    ("Stanton4b_ASD_Delving_Facility_007", "Onyx Facility S4B7"),
    ("Stanton4b_ASD_Delving_Facility_008", "Onyx Facility S4B8"),
    ("Stanton4b_ASD_Delving_Facility_009", "Onyx Facility S4B9"),
    ("Stanton4b_ASD_Delving_Facility_010", "Onyx Facility S4B10"),
    ("Stanton4b_Racetrack_SnakePit", "The Snake Pit"),
    ("Stanton4b_Rayari_001", "Rayari McGrath Research Outpost"),
    ("Stanton4b_Rayari_002", "Rayari Cantwell Research Outpost"),
    ("Stanton4c", "Euterpe"),
    ("Stanton4c_ASD_Delving_Facility_001", "Onyx Facility S4C1"),
    ("Stanton4c_ASD_Delving_Facility_002", "Onyx Facility S4C2"),
    ("Stanton4c_ASD_Delving_Facility_003", "Onyx Facility S4C3"),
    ("Stanton4c_ASD_Delving_Facility_004", "Onyx Facility S4C4"),
    ("Stanton4c_ASD_Delving_Facility_005", "Onyx Facility S4C5"),
    ("Stanton4c_ASD_Delving_Facility_006", "Onyx Facility S4C6"),
    ("Stanton4c_ASD_Delving_Facility_007", "Onyx Facility S4C7"),
    ("Stanton4c_ASD_Delving_Facility_008", "Onyx Facility S4C8"),
    ("Stanton4c_ASD_Delving_Facility_009", "Onyx Facility S4C9"),
    ("Stanton4c_ASD_Delving_Facility_010", "Onyx Facility S4C10"),
    ("Stanton4c_IndyFarmer_001", "Bud's Growery"),
    ("Stanton4c_Racetrack_Icebreaker", "The Icebreaker"),
    ("Stanton4c_SalvageYard_001", "Devlin Scrap & Salvage"),
    ("Stanton_2", "Stanton (Star)"),
    ("Stanton_JumpPoint_Magnus", "Stanton - Magnus Jump Point"),
    ("Stanton_JumpPoint_Pyro", "Stanton-Pyro Jump Point"),
    (
        "Stanton_JumpPoint_Pyro_WreckSite",
        "Stanton-Pyro Jump Point Wreck Site",
    ),
    ("Stanton_JumpPoint_Terra", "Stanton - Terra Jump Point"),
    ("Stanton_Magnus_JPStation", "Magnus Gateway"),
    ("Stanton_Magnus_JPStation_clinic", "Magnus Gateway Clinic"),
    ("Stanton_Pyro_JPStation", "Pyro Gateway"),
    ("Stanton_Pyro_JPStation_clinic", "Pyro Gateway Clinic"),
    ("Stanton_Terra_JPStation", "Terra Gateway"),
    ("Stanton_Terra_JPStation_clinic", "Terra Gateway Clinic"),
    ("StantonStar", "Stanton"),
    ("StantonSystem", "Stanton"),
    ("ui_pregame_port_Area18_name", "Area18"),
    ("ui_pregame_port_Checkmate_name", "Checkmate"),
    ("ui_pregame_port_GrimHex_name", "Grim HEX"),
    ("ui_pregame_port_Levski_name", "Levski"),
    ("ui_pregame_port_Lorville_name", "Lorville"),
    (
        "ui_pregame_port_MileMillionHighClub_name",
        "Million Mile High Club",
    ),
    ("ui_pregame_port_NewBabbage_name", "New Babbage"),
    ("ui_pregame_port_Olisar_name", "Port Olisar"),
    ("ui_pregame_port_Orison_name", "Orison"),
    ("hangar_01", "PYAM-EXHANG-0-1 Hangar"),
    ("hangar_02", "PYAM-EXHANG-0-1 Hangar"),
    ("hangar_03", "PYAM-EXHANG-0-1 Hangar"),
];
