const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');

export function previewHtml(manifest, names=[...new Set(manifest.outputs.map(output=>output.layer))]) {
  const sections=names.map(name=>{
    const outputs=manifest.outputs.filter(output=>output.layer===name);
    const video=outputs.find(output=>output.format==='webm')??outputs.find(output=>output.format==='mp4');
    const still=outputs.find(output=>['png','webp','jpg'].includes(output.format));
    const media=video?`<video controls loop muted playsinline preload="metadata" ${still?`poster="${escape(still.file)}"`:''} src="${escape(video.file)}"></video>`:`<img src="${escape(still?.file??`${name}/frames/000000.png`)}">`;
    return `<section id="${escape(name)}"><h2>${escape(name)}</h2><div class="canvas">${media}</div><p>${outputs.filter(output=>output.format!=='frames').map(output=>`<a href="${escape(output.file)}">${escape(output.format==='mov'?'ProRes 4444 MOV':output.format)}</a>`).join(' ')}</p></section>`;
  }).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ClipLib alpha review</title><style>:root{--matte:repeating-conic-gradient(#36363b 0 25%,#252529 0 50%) 0/24px 24px}body{font:15px/1.5 system-ui;background:#151518;color:#eee;margin:32px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,440px),1fr));gap:24px}h2{font-size:16px}a{color:#d6aaff;margin-right:16px}.canvas{background:var(--matte)}img,video{display:block;width:100%;background:transparent}button{font:inherit;padding:8px 14px;border:1px solid #666;border-radius:6px;color:inherit;background:#29292e;cursor:pointer;margin:0 8px 8px 0}button[aria-pressed=true]{outline:2px solid #c9a1ff}nav{position:sticky;top:0;background:#151518;padding:10px 0;z-index:1}</style><h1>ClipLib alpha review</h1><p>${escape(manifest.scene)} / ${escape(manifest.dimensionsLabel ?? `${manifest.width} × ${manifest.height}`)} / ${manifest.fps} fps. <a href="manifest.json">Manifest</a></p><nav aria-label="Preview background"><button data-bg="checker" aria-pressed="true">Checkerboard</button><button data-bg="dark" aria-pressed="false">Dark</button><button data-bg="light" aria-pressed="false">Light</button><button data-bg="blue" aria-pressed="false">Blue</button></nav><p>Change the background to inspect soft glow edges. MP4 is opaque. WebM needs an alpha-capable decoder; use PNG sequences or ProRes 4444 for editing when WebM alpha is unsupported. Isolated screen-blended glows need Screen blending in the editor.</p><main>${sections}</main><script>const backgrounds={checker:'repeating-conic-gradient(#36363b 0 25%,#252529 0 50%) 0/24px 24px',dark:'#111114',light:'#eeeeee',blue:'#24486a'};document.querySelectorAll('[data-bg]').forEach(button=>button.addEventListener('click',()=>{document.documentElement.style.setProperty('--matte',backgrounds[button.dataset.bg]);document.querySelectorAll('[data-bg]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));}));</script></html>`;
}
