[package]
name = "clipdip-profile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
parking_lot.workspace = true
tracing.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Performance",
] }
