//! VeeLume vessels.json (MIT); license retained beside this file
pub const SHIPS: &[(&str, &str, &str)] = &[
    ("sidewinder", "Sidewinder", "sidewinder"),
    ("eagle", "Eagle", "eagle"),
    ("hauler", "Hauler", "hauler"),
    ("adder", "Adder", "adder"),
    ("empire_eagle", "Imperial Eagle", "imperial-eagle"),
    ("viper", "Viper Mk III", "viper-mk-iii"),
    ("cobramkiii", "Cobra Mk III", "cobra-mk-iii"),
    ("viper_mkiv", "Viper Mk IV", "viper-mk-iv"),
    ("diamondback", "Diamondback Scout", "diamondback-scout"),
    ("cobramkiv", "Cobra Mk IV", "cobra-mk-iv"),
    ("type6", "Type-6 Transporter", "type-6-transporter"),
    ("dolphin", "Dolphin", "dolphin"),
    (
        "diamondbackxl",
        "Diamondback Explorer",
        "diamondback-explorer",
    ),
    ("empire_courier", "Imperial Courier", "imperial-courier"),
    ("independant_trader", "Keelback", "keelback"),
    ("asp_scout", "Asp Scout", "asp-scout"),
    ("vulture", "Vulture", "vulture"),
    ("asp", "Asp Explorer", "asp-explorer"),
    (
        "federation_dropship",
        "Federal Dropship",
        "federal-dropship",
    ),
    ("type7", "Type-7 Transporter", "type-7-transporter"),
    ("typex", "Alliance Chieftain", "alliance-chieftain"),
    (
        "federation_dropship_mkii",
        "Federal Assault Ship",
        "federal-assault-ship",
    ),
    ("empire_trader", "Imperial Clipper", "imperial-clipper"),
    ("typex_2", "Alliance Crusader", "alliance-crusader"),
    ("typeex_3", "Alliance Challenger", "alliance-challenger"),
    ("federation_gunship", "Federal Gunship", "federal-gunship"),
    ("krait_light", "Krait Phantom", "krait-phantom"),
    ("krait_mkii", "Krait Mk II", "krait-mk-ii"),
    ("orca", "Orca", "orca"),
    ("ferdelance", "Fer-de-Lance", "fer-de-lance"),
    ("mamba", "Mamba", "mamba"),
    ("python", "Python", "python"),
    ("python_nx", "Python Mk II", "python-mk-ii"),
    ("type9", "Type-9 Heavy", "type-9-heavy"),
    ("belugaliner", "Beluga Liner", "beluga-liner"),
    ("type9_military", "Type-10 Defender", "type-10-defender"),
    ("anaconda", "Anaconda", "anaconda"),
    (
        "federation_corvette",
        "Federal Corvette",
        "federal-corvette",
    ),
    ("cutter", "Imperial Cutter", "imperial-cutter"),
    ("cobramkv", "Cobra Mk V", "cobra-mk-v"),
    ("type8", "Type-8 Transporter", "type-8-transporter"),
    (
        "panthermkii",
        "Panther Clipper Mk II",
        "panther-clipper-mk-ii",
    ),
    ("corsair", "Corsair", "corsair"),
    ("mandalay", "Mandalay", "mandalay"),
    ("typex_3", "Alliance Challenger", "alliance-challenger"),
];
