[package]
name = "clipdip-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
chrono.workspace = true
serde_json.workspace = true
toml.workspace = true
directories.workspace = true
windows.workspace = true
windows-core.workspace = true

clipdip-capture.workspace = true
clipdip-encoder.workspace = true
clipdip-audio.workspace = true
clipdip-ringbuf.workspace = true
clipdip-muxer.workspace = true
clipdip-hotkey.workspace = true
clipdip-profile.workspace = true
